/**
 * Generates the stub `node_modules/@minecraft/server` and `/server-ui` packages.
 *
 * Node's ESM loader resolves bare specifiers through `node_modules` and does not
 * let a test hook intercept them the way CommonJS `Module._load` does. The engine
 * therefore has to be tested against real files on disk, and this script writes
 * them: a tiny package whose exports are the fakes in `mc-stub.mjs`.
 *
 * `node_modules/` is gitignored, so generation is part of `npm test`. Running it
 * is idempotent.
 *
 * Usage: node tools/test/gen-stubs.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from '../lib/repo.mjs';

const MODULES = {
  '@minecraft/server': '2.0.0',
  '@minecraft/server-ui': '2.0.0',
};

const ENTRY = `/**
 * GENERATED by tools/test/gen-stubs.mjs - do not edit.
 *
 * Re-exports the fake Minecraft API used by the test suite.
 */
export * from '@msu-test/stub';
`;

const UI_ENTRY = `/**
 * GENERATED by tools/test/gen-stubs.mjs - do not edit.
 */
export * from '@msu-test/stub-ui';
`;

for (const [name, version] of Object.entries(MODULES)) {
  const dir = join(ROOT, 'node_modules', name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'package.json'), `${JSON.stringify({
    name,
    version,
    type: 'module',
    main: 'index.js',
    exports: { '.': './index.js' },
  }, null, 2)}\n`);
  writeFileSync(join(dir, 'index.js'), name.endsWith('server-ui') ? UI_ENTRY : ENTRY);
}

// The stub implementation itself lives in tools/test and is exposed to the engine
// through these two shim packages.
for (const [name, target] of [
  ['@msu-test/stub', 'mc-stub.mjs'],
  ['@msu-test/stub-ui', 'mc-stub-ui.mjs'],
]) {
  const dir = join(ROOT, 'node_modules', name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'package.json'), `${JSON.stringify({
    name,
    version: '1.0.0',
    type: 'module',
    main: 'index.js',
    exports: { '.': './index.js' },
  }, null, 2)}\n`);
  writeFileSync(join(dir, 'index.js'), `export * from ${JSON.stringify(new URL(target, import.meta.url).href)};\n`);
}

console.log('gen-stubs: wrote node_modules/@minecraft/server and node_modules/@minecraft/server-ui');